ga:
  id: UA-60309485-1

facebook:
  id: 936788093105150
  secret: db39b3e4f615eddfe373fe6a1086e8ac
  options:
    scope: 'email'
    info_fields: 'name,email'

vkontakte:
  id: 5444900
  secret: KvpsLpKt48BDSXiv4rJb
  options:
    scope: 'notify'