facebook:
  id: 113612365714244
  secret: 677c484898ffd73cd58298ce76ee8983
  options:
    scope: 'email'
    info_fields: 'name,email'

vkontakte:
  id: 5444895
  secret: nwtBEdwzuPaxrCNT8Rvo
  options:
    scope: 'notify'